### ISSUE TITLE
Can not get DataChannel from LocalPeer instance

### ISSUE THREAD

**Issue by xsvetli1** [Innovailable/rtc-lib#1]
It is impossible to send message through DataChannel that I added to LocalPeer (Room.local.addDataChannel), because I don't have option to get this channel, when I want to call send() method on it.

**Comment by xsvetli1** [comment]
Is there way to overcome this problem, or will this be implemented soon please?

**Comment by thammi** [comment]
The `LocalPeer` can't give you a `DataChannel` because it is only a helper to set up you streams and channels for every `RemotePeer`. Only a `RemotePeer` can actually give you a channel and remote streams because they represent the other participants of the session you want to communicate with.

After adding the channel to the `LocalPeer` you can get the `DataChannel` from every `RemotePeer` using `RemotePeer.channel()`.

**Comment by xsvetli1** [comment]
Oh, alright.. I finally understood it and it is working. Thank you very much for fast response!!!
